#!/usr/bin/env bash
# hlfi - hledger project finance scripts
# shellcheck shell=bash disable=SC2317

set -e
cd "$(dirname "$0")"
SCRIPT=$(basename "$0")
JOURNAL=oc.journal
PERIOD="quarterly from 1/1 to tomorrow"

line() { echo "--------------------------------------------------------------------------------"; }

help() { # - show this help
    line
    cat <<EOF
hlfi - hledger project finance tool
Usage: hlfi [COMMAND]
Commands:
$(grep -E '^\w.*\(\) *{ *#' "$SCRIPT" | sed -e 's/() *{//' -e 's/# /\t/')
CMD 	- run other hledger commands on the hledger project's journal

Add hledger options to customise reports.
EOF
}

bs() { # - show balance sheet
    hledger -f "$JOURNAL" bs --layout bare --pretty --drop 1 -p "$PERIOD" -E "$@"
}

is() { # - show income statement
    hledger -f "$JOURNAL" is --layout bare --pretty --drop 1 -p "$PERIOD" -S "$@"
}

a() { # - show assets
    hledger -f "$JOURNAL" bal type:al -H --layout bare --pretty --drop 1 -p "$PERIOD" -E "$@"
}

r() { # - show revenues
    hledger -f "$JOURNAL" bal type:r --layout bare --pretty --drop 1 -p "$PERIOD" -S --invert "$@"
}

x() { # - show expenses
    hledger -f "$JOURNAL" bal type:x --layout bare --pretty --drop 1 -p "$PERIOD" -S --invert "$@"
}

b-a() { # - show assets bar chart
    hledger-bar -v 200 -f "$JOURNAL" -Q type:al -H "$@"
}

b-r() { # - show revenues bar chart
    hledger-bar -v 40 -f "$JOURNAL" -Q type:r --invert "$@"
}

b-x() { # - show expenses bar chart
    hledger-bar -v 40 -f "$JOURNAL" -Q type:x --invert "$@"
}

# XXX with partial workaround for https://github.com/gooofy/drawilleplot/issues/4
l-a() { # - show assets line chart
    hledger -f "$JOURNAL" plot -- bal --depth=1 ^assets   --historical  --terminal --rcParams '{"figure.figsize":[8,3]}' --no-today -q --title "hledger assets" "$@" | sed 's/⠀/ /g'
}

l-r() { # - show revenues line chart
    hledger -f "$JOURNAL" plot -- bal --depth=1 ^revenues --monthly --invert  --terminal --rcParams '{"figure.figsize":[8,3]}' --drawstyle 'steps-mid' --no-today -q --title "hledger monthly revenues" "$@" | sed 's/⠀/ /g'
}

l-x() { # - show expenses line chart
    hledger -f "$JOURNAL" plot -- bal --depth=1 ^expenses --monthly --terminal --rcParams '{"figure.figsize":[8,3]}' --drawstyle 'steps-mid' --no-today -q --title "hledger monthly expenses" "$@" | sed 's/⠀/ /g'
}

if [[ $# -eq 0 ]]; then help                  # no args shows help
elif declare -f "$1" > /dev/null; then "$@";  # arg 1 selects a function above
else hledger -f "$JOURNAL" "$@"; fi           # or fall through to hledger
exit
